import Agis.Localisation.*

@addMethod(gameuiInGameMenuGameController)
protected cb func RegisterAGISARASAKAACWStore(event: ref<VirtualShopRegistration>) -> Bool {
  event.AddStore(
    n"AGISARASAKAACW",
    agisName().arasaka,
    ["Items.AdvancedStrongArmsElectricLegendary", "Items.AdvancedMantisBladesElectricLegendary", "Items.AdvancedNanoWiresElectricLegendary", "Items.AdvancedProjectileLauncherElectricLegendary", "Items.AdvancedStrongArmsLegendary", "Items.AdvancedMantisBladesLegendary", "Items.AdvancedNanoWiresLegendary", "Items.AdvancedProjectileLauncherLegendary", "Items.AdvancedStrongArmsThermalLegendary", "Items.AdvancedMantisBladesThermalLegendary", "Items.AdvancedNanoWiresThermalLegendary", "Items.AdvancedProjectileLauncherThermalLegendary", "Items.AdvancedStrongArmsChemicalLegendary", "Items.AdvancedMantisBladesChemicalLegendary", "Items.AdvancedNanoWiresChemicalLegendary", "Items.AdvancedProjectileLauncherChemicalLegendary", "Items.AdvancedStrongArmsElectricEpic", "Items.AdvancedMantisBladesElectricEpic", "Items.AdvancedNanoWiresElectricEpic", "Items.AdvancedProjectileLauncherElectricEpic", "Items.AdvancedStrongArmsEpic", "Items.AdvancedMantisBladesEpic", "Items.AdvancedNanoWiresEpic", "Items.AdvancedProjectileLauncherEpic", "Items.AdvancedStrongArmsThermalEpic", "Items.AdvancedMantisBladesThermalEpic", "Items.AdvancedNanoWiresThermalEpic", "Items.AdvancedProjectileLauncherThermalEpic", "Items.AdvancedStrongArmsChemicalEpic", "Items.AdvancedMantisBladesChemicalEpic", "Items.AdvancedNanoWiresChemicalEpic", "Items.AdvancedProjectileLauncherChemicalEpic", "Items.AdvancedStrongArmsElectricRare", "Items.AdvancedMantisBladesElectricRare", "Items.AdvancedNanoWiresElectricRare", "Items.AdvancedProjectileLauncherElectricRare", "Items.AdvancedStrongArmsRare", "Items.AdvancedMantisBladesRare", "Items.AdvancedNanoWiresRare", "Items.AdvancedProjectileLauncherRare", "Items.AdvancedStrongArmsThermalRare", "Items.AdvancedMantisBladesThermalRare", "Items.AdvancedNanoWiresThermalRare", "Items.AdvancedProjectileLauncherThermalRare", "Items.AdvancedStrongArmsChemicalRare", "Items.AdvancedMantisBladesChemicalRare", "Items.AdvancedNanoWiresChemicalRare", "Items.AdvancedProjectileLauncherChemicalRare", "Items.AdvancedStrongArmsElectricUncommon", "Items.AdvancedMantisBladesElectricUncommon", "Items.AdvancedNanoWiresElectricUncommon", "Items.AdvancedProjectileLauncherElectricUncommon", "Items.AdvancedStrongArmsUncommon", "Items.AdvancedMantisBladesUncommon", "Items.AdvancedNanoWiresUncommon", "Items.AdvancedProjectileLauncherUncommon", "Items.AdvancedStrongArmsThermalUncommon", "Items.AdvancedMantisBladesThermalUncommon", "Items.AdvancedNanoWiresThermalUncommon", "Items.AdvancedProjectileLauncherThermalUncommon", "Items.AdvancedStrongArmsChemicalUncommon", "Items.AdvancedMantisBladesChemicalUncommon", "Items.AdvancedNanoWiresChemicalUncommon", "Items.AdvancedProjectileLauncherChemicalUncommon"],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    r"base/gameplay/gui/agis-pn_store.inkatlas",
    n"pn_arasaka",
    ["Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon"],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  );
}