import Agis.Localisation.*

@addMethod(gameuiInGameMenuGameController)
protected cb func RegisterAGISDATAINCHACKSStore(event: ref<VirtualShopRegistration>) -> Bool {
  event.AddStore(
    n"AGISDATAINCHACKS",
    agisName().datainc,
    ["Items.WhistleLvl4Program", "Items.ContagionLvl4Program", "Items.LocomotionMalfunctionLvl4Program", "Items.MadnessLvl4Program", "Items.DisableCyberwareLvl4Program", "Items.GrenadeExplodeLvl4Program", "Items.MemoryWipeLvl4Program", "Items.OverheatLvl4Program", "Items.PingLvl4Program", "Items.BlindLvl4Program", "Items.CommsCallInLvl4Program", "Items.EMPOverloadLvl4Program", "Items.CommsNoiseLvl4Program", "Items.SuicideLvl4Program", "Items.BrainMeltLvl4Program", "Items.SystemCollapseLvl4Program", "Items.WeaponMalfunctionLvl4Program", "Items.WhistleLvl3Program", "Items.ContagionLvl3Program", "Items.LocomotionMalfunctionLvl3Program", "Items.MadnessLvl3Program", "Items.DisableCyberwareLvl3Program", "Items.GrenadeExplodeLvl3Program", "Items.MemoryWipeLvl3Program", "Items.OverheatLvl3Program", "Items.PingLvl3Program", "Items.BlindLvl3Program", "Items.CommsCallInLvl3Program", "Items.EMPOverloadLvl3Program", "Items.CommsNoiseLvl3Program", "Items.SuicideLvl3Program", "Items.BrainMeltLvl3Program", "Items.SystemCollapseLvl3Program", "Items.WeaponMalfunctionLvl3Program", "Items.WhistleLvl2Program", "Items.ContagionLvl2Program", "Items.LocomotionMalfunctionLvl2Program", "Items.DisableCyberwareLvl2Program", "Items.MemoryWipeLvl2Program", "Items.OverheatLvl2Program", "Items.PingLvl2Program", "Items.BlindLvl2Program", "Items.CommsCallInLvl2Program", "Items.EMPOverloadLvl2Program", "Items.CommsNoiseLvl2Program", "Items.BrainMeltLvl2Program", "Items.WeaponMalfunctionLvl2Program", "Items.WhistleLvl1Program", "Items.ContagionProgram", "Items.LocomotionMalfunctionProgram", "Items.DisableCyberwareProgram", "Items.OverheatLvl1Program", "Items.BlindLvl1Program", "Items.CommsCallInLvl1Program", "Items.EMPOverloadLvl1Program", "Items.CommsNoiseProgram", "Items.WeaponMalfunctionProgram", "Items.WhistleLvl0Program", "Items.OverheatProgram", "Items.PingProgram", "Items.BlindProgram", "Items.EMPOverloadProgram"],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    r"base/gameplay/gui/agis-pn_store.inkatlas",
    n"pn_datainc",
    ["Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Common", "Common", "Common", "Common", "Common"],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  );
}