import Agis.Localisation.*

@addMethod(gameuiInGameMenuGameController)
protected cb func RegisterAGISEDGENETHACKSStore(event: ref<VirtualShopRegistration>) -> Bool {
  event.AddStore(
    n"AGISEDGENETHACKS",
    agisName().edgenet,
    ["Items.Recipe_WhistleLvl4Program", "Items.Recipe_ContagionLvl4Program", "Items.Recipe_LocomotionMalfunctionLvl4Program", "Items.Recipe_MadnessLvl4Program", "Items.Recipe_DisableCyberwareLvl4Program", "Items.Recipe_GrenadeExplodeLvl4Program", "Items.Recipe_MemoryWipeLvl4Program", "Items.Recipe_OverheatLvl4Program", "Items.Recipe_PingLvl4Program", "Items.Recipe_BlindLvl4Program", "Items.Recipe_CommsCallInLvl4Program", "Items.Recipe_EMPOverloadLvl4Program", "Items.Recipe_CommsNoiseLvl4Program", "Items.Recipe_SuicideLvl4Program", "Items.Recipe_BrainMeltLvl4Program", "Items.Recipe_SystemCollapseLvl4Program", "Items.Recipe_WeaponMalfunctionLvl4Program", "Items.Recipe_WhistleLvl3Program", "Items.Recipe_ContagionLvl3Program", "Items.Recipe_LocomotionMalfunctionLvl3Program", "Items.Recipe_MadnessLvl3Program", "Items.Recipe_DisableCyberwareLvl3Program", "Items.Recipe_GrenadeExplodeLvl3Program", "Items.Recipe_MemoryWipeLvl3Program", "Items.Recipe_OverheatLvl3Program", "Items.Recipe_PingLvl3Program", "Items.Recipe_BlindLvl3Program", "Items.Recipe_CommsCallInLvl3Program", "Items.Recipe_EMPOverloadLvl3Program", "Items.Recipe_CommsNoiseLvl3Program", "Items.Recipe_SuicideLvl3Program", "Items.Recipe_BrainMeltLvl3Program", "Items.Recipe_SystemCollapseLvl3Program", "Items.Recipe_WeaponMalfunctionLvl3Program", "Items.Recipe_WhistleLvl2Program", "Items.Recipe_ContagionLvl2Program", "Items.Recipe_LocomotionMalfunctionLvl2Program", "Items.Recipe_DisableCyberwareLvl2Program", "Items.Recipe_MemoryWipeLvl2Program", "Items.Recipe_OverheatLvl2Program", "Items.Recipe_PingLvl2Program", "Items.Recipe_BlindLvl2Program", "Items.Recipe_CommsCallInLvl2Program", "Items.Recipe_EMPOverloadLvl2Program", "Items.Recipe_CommsNoiseLvl2Program", "Items.Recipe_BrainMeltLvl2Program", "Items.Recipe_WeaponMalfunctionLvl2Program", "Items.Recipe_WhistleLvl1Program", "Items.Recipe_ContagionProgram", "Items.Recipe_LocomotionMalfunctionProgram", "Items.Recipe_DisableCyberwareProgram", "Items.Recipe_OverheatLvl1Program", "Items.Recipe_OverheatProgram", "Items.Recipe_PingProgram", "Items.Recipe_BlindLvl1Program", "Items.Recipe_BlindProgram", "Items.Recipe_CommsCallInLvl1Program", "Items.Recipe_CommsCallInProgram", "Items.Recipe_EMPOverloadLvl1Program", "Items.Recipe_EMPOverloadProgram", "Items.Recipe_CommsNoiseProgram", "Items.Recipe_WeaponMalfunctionProgram"],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    r"base/gameplay/gui/agis-pn_store.inkatlas",
    n"pn_edgenet",
    ["Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Legendary", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Epic", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Rare", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon", "Uncommon"],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  );
}